version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongo-trainuvo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: trainuvo
      MONGO_INITDB_ROOT_PASSWORD: trainuvo123
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: